name: Test
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        
      - name: Install dependencies
        run: |
          pip install .
          pip install pytest pytest-cov
          
      - name: Run tests with cover
        run: |
          pytest --cov=src
          
      - name: Codecov badge
        uses: codecov/codecov-action@v3
